import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from '../components/navbar'
import FlowbiteContext from '@/context/flowbite'
import { ApolloWrapper } from '@/lib/apollo-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-white max-w-7xl mx-auto px-6">
        <FlowbiteContext>
          <ApolloWrapper>
            <NavBar/>
            {children}
            </ApolloWrapper>
          </FlowbiteContext>;
      </body>
    </html>
  )
}
