import '../globals.css'
import NavBar from '@/components/navbar'
import Bottom from '@/components/footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col min-h-screen">
      <div className="flex flex-grow justify-center items-center">{children}</div>
      <div className="w-full">
        <Bottom />
      </div>
    </div>
  )
}
