// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthOps struct {
	Login        interface{} `json:"login"`
	Register     interface{} `json:"register"`
	SpotifyLogin interface{} `json:"spotifyLogin"`
}

type NewUser struct {
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`
	Password    string `json:"password"`
}

type RecommendationsInput struct {
	Period string `json:"period"`
}

type Release struct {
	ID            int       `json:"_id"`
	Title         string    `json:"title"`
	Artists       []string  `json:"artists"`
	Featurings    []string  `json:"featurings,omitempty"`
	Date          time.Time `json:"date"`
	Cover         *string   `json:"cover,omitempty"`
	Genres        []string  `json:"genres,omitempty"`
	Producers     []string  `json:"producers,omitempty"`
	Tracklist     []string  `json:"tracklist,omitempty"`
	Type          string    `json:"type"`
	AotyID        *string   `json:"aoty_id,omitempty"`
	TrendingScore *float64  `json:"trending_score,omitempty"`
}

type ReleasesInput struct {
	Type      string `json:"type"`
	Direction string `json:"direction"`
	Reference int    `json:"reference"`
	Period    string `json:"period"`
}

type ReleasesList struct {
	Releases []*Release `json:"releases"`
	Prev     bool       `json:"prev"`
	Next     bool       `json:"next"`
}
