package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"
	"main/db"
	"main/graph/model"
)

// TrendingReleases is the resolver for the trendingReleases field.
func (r *queryResolver) TrendingReleases(ctx context.Context, input model.ReleasesInput) (*model.ReleasesList, error) {
	return db.GetTrendingReleases(input.Type, input.Direction, input.Reference, input.Period), nil
}

// Release is the resolver for the release field.
func (r *queryResolver) Release(ctx context.Context, id int) (*model.Release, error) {
	return db.GetRelease(id), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
