import '../globals.css'
import Bottom from '@/components/footer'
import NavBar from '@/components/navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <NavBar/>
        {children}
    <Bottom/>
    </>
  )
}
